### ISSUE TITLE
Caching "shared" throws an error.

### ISSUE THREAD

**Issue by rohithpr** [advertine/node-ip2location#3]
`var location = new Location('./lib/IP2LOCATION-LITE-DB9.BIN', 'shared');`

causes:

```
Error: could not open IP2LOCATION database
    at Error (native)
    at /home/user/dir/lib/file1.js:10:18
    at Object.<anonymous> (/home/user/dir/lib/file1.js:367:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/user/dir/lib/controllers/file2.js:19:17
```

It works when caching is set to `cache`, `mmap` or not set.

DB file: latest (July 2016)
Node: 4.4.7
ip2location-native: 1.1.2

**Comment by royaltm** [comment]
My guess is that you have upgraded the database file and tried to open new version while still having an old version in shared memory. You must first delete shared file containing old version of the database.
On linux the simplest way is to: `rm /dev/shm/IP2location_Shm`.
You can also use `ipcs` and `ipcrm` tools.

To delete shared file from within this library you have to open old database version first (the exactly same version that is residing in shared memory), then call `location.deleteShared()` and `location.close()`.

Alternatively you may assign a unique name to your shared database calling:

```
var location = new Location('./lib/IP2LOCATION-LITE-DB9.BIN', '/ip2location_July_2016');
```

**Comment by rohit-gohri** [comment]
We could use the modified date of the bin file as a suffix for the shared memory name?

**Comment by royaltm** [comment]
...this or append a hash of a content of a DB file to the shared name. However please keep in mind that you need to clean up the old shared map files sooner or later, otherwise you may clutter up the shared memory on the server.
